services:
  postgres:
    image: postgres
    volumes:
      - pgdata-2:/var/lib/postgresql/data 
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - db-network
  db-update:
    build:
      context: .
      dockerfile: ./packages/db/Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/postgres
    networks:
      - db-network
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    environment:
      - CORS_ORIGINS=https://esc.sashkahavr.dev
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/postgres
    networks:
      - db-network
    env_file:
      - path: .env
    ports:
      - 5240:3000
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        - VITE_API_URL=https://api.esc.sashkahavr.dev
    ports:
      - 5241:3000

networks:
  db-network:

volumes:
  pgdata-2: