services:
  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data 
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - db-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  db-update:
    build:
      context: .
      dockerfile: ./packages/db/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/postgres
    networks:
      - db-network
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - CORS_ORIGINS=http://localhost:5241
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/postgres
    networks:
      - db-network
    env_file:
      - path: .env
    ports:
      - 5240:3000
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        - VITE_API_URL=https://api.esc.sashkahavr.dev
    ports:
      - 5241:3000

networks:
  db-network:

volumes:
  pgdata: